In [17]:
import pandas as pd
from numpy.random import randn
df=pd.DataFrame(randn(5,5,),index='A B C D E'.split(),columns='V W X Y Z'.split())
df
df['NEW']=df['W']+df['Y']
df['NEW1']=[1,2,3,4,5]
df['NEW2']=100
df

          V         W         X         Y         Z       NEW  NEW1  NEW2
A -0.736743  0.539549  1.862709 -0.825044 -0.971656 -0.285495     1   100
B -0.659250 -0.066343  0.163158 -0.690198 -0.579971 -0.756541     2   100
C  0.084041  1.109184  0.290108 -0.519891  0.843162  0.589293     3   100
D -0.531417 -1.209989 -1.289725 -1.183160 -0.423529 -2.393149     4   100
E  0.089380  0.147798 -0.119364 -0.032739 -1.032248  0.115059     5   100

In [22]:
#Drop function
a=df.drop('NEW1',axis=1)
a

          V         W         X         Y         Z       NEW  NEW2
A -0.736743  0.539549  1.862709 -0.825044 -0.971656 -0.285495   100
B -0.659250 -0.066343  0.163158 -0.690198 -0.579971 -0.756541   100
C  0.084041  1.109184  0.290108 -0.519891  0.843162  0.589293   100
D -0.531417 -1.209989 -1.289725 -1.183160 -0.423529 -2.393149   100
E  0.089380  0.147798 -0.119364 -0.032739 -1.032248  0.115059   100

In [25]:
df.drop("Y",axis=1,inplace=True)
df.drop("D",axis=0,inplace=True)
df

          V         W         X         Z       NEW  NEW1  NEW2
A -0.736743  0.539549  1.862709 -0.971656 -0.285495     1   100
B -0.659250 -0.066343  0.163158 -0.579971 -0.756541     2   100
C  0.084041  1.109184  0.290108  0.843162  0.589293     3   100
E  0.089380  0.147798 -0.119364 -1.032248  0.115059     5   100

In [40]:
#DEL AND POP FUNCTION TO REMOVE COLUMN ONLY
import pandas as pd
from numpy.random import randn
df=pd.DataFrame(randn(5,5,),index='A B C D E'.split(),columns='V W X Y Z'.split())
df
del df["V"]
df.pop("X")
df

          W         Y         Z
A -1.754336  0.582511 -1.342425
B  0.119464 -0.596883  0.150791
C  1.152527  1.754394 -1.461443
D  0.938229 -2.049649 -2.272985
E  0.871637  1.169394  0.300191

In [49]:
#Concat and ignore_index
df1=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[5,6],[7,8]],columns=['a','b'])
df=pd.concat([df1,df2])
print(df)
df=pd.concat([df1,df2],ignore_index=True)
df

   a  b
0  1  2
1  3  4
0  5  6
1  7  8

   a  b
0  1  2
1  3  4
2  5  6
3  7  8

In [52]:
#reset_index and set_index
df=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df.reset_index(drop=True)
df.set_index("a")
df

   a  b
0  1  2
1  3  4

In [59]:
from numpy.random import randn
df=pd.DataFrame(np.random.randn(5,5),columns='V W X Y Z'.split())
df

          V         W         X         Y         Z
0  0.735376  0.808823 -0.046656 -0.387710 -0.447981
1 -1.263088 -0.013005  0.138956  1.290163  0.805123
2  0.103381 -0.432730 -0.522589 -0.842885  1.415255
3 -0.370324  1.286564 -1.542948 -0.201881  0.143991
4 -0.237272  0.951333  0.796828 -0.319501  0.672709

In [61]:

df.drop([0],axis=0,inplace=True)
df.drop([4],axis=0,inplace=True)

In [62]:
df

          V         W         X         Y         Z
1 -1.263088 -0.013005  0.138956  1.290163  0.805123
2  0.103381 -0.432730 -0.522589 -0.842885  1.415255
3 -0.370324  1.286564 -1.542948 -0.201881  0.143991

In [66]:
a=df.reset_index(drop=True)
a

          V         W         X         Y         Z
0 -1.263088 -0.013005  0.138956  1.290163  0.805123
1  0.103381 -0.432730 -0.522589 -0.842885  1.415255
2 -0.370324  1.286564 -1.542948 -0.201881  0.143991

In [68]:
b=df.set_index("W")
b

                  V         X         Y         Z
W
-0.013005 -1.263088  0.138956  1.290163  0.805123
-0.432730  0.103381 -0.522589 -0.842885  1.415255
 1.286564 -0.370324 -1.542948 -0.201881  0.143991